export interface Order {
  orderId: string,
  orderName?: string,
  entryDate?: string,
  placedDate?: string,
  approvedDate?: string,
  completedDate?: string,
  statusId?: string,
  processingStatusId?: string,
  orderRevision?: number,
  currencyUomId?: string,
  billingAccountId?: string,
  productStoreId?: string,
  salesChannelEnumId?: string,
  externalId?: string,
  externalRevision?: string,
  originId?: string,
  originUrl?: string,
  syncStatusId?: string, 
  systemMessageRemoteId?: string,
  enteredByPartyId?: string,
  parentOrderId?: string,
  lastOrderedDate?: string,
  recurAutoInvoice?: string,
  remainingSubTotal?: number,
  grandTotal?: number,
  notes?: Array<{
    orderId: string,
    noteDate: string,
    noteText?: string,
    internalNote?: string,
    userId?: string,
  }>,
  communicationEvents?: Array<{
    orderId: string,
    communicationEventId: string
  }>
}
