import { Enumeration, Geo, Status, Party, Uom } from "./index"

export interface Product {
  productId: string,
  pseudoId?: string,
  productTypeEnumId?: string,
  productClassEnumId?: string,
  assetTypeEnumId?: string,
  assetClassEnumId?: string,
  statusId?: string,
  ownerPartyId?: string,
  productName?: string,
  description?: string,
  comments?: string,
  salesIntroductionDate?: string,
  salesDiscontinuationDate?: string,
  salesDiscWhenNotAvail?: string,
  supportDiscontinuationDate?: string,
  requireInventory?: string,
  chargeShipping?: string,
  signatureRequiredEnumId?: string,
  shippingInsuranceReqd?: string,
  inShippingBox?: string,
  defaultShipmentBoxTypeId?: string,
  taxable?: string,
  taxCode?: string,
  returnable?: string,
  amountUomId?: string,
  amountFixed?: 0,
  amountRequire?: string,
  originGeoId?: string,
  type?: Enumeration,
  class?: Enumeration,
  assetType?: Enumeration,
  assetClass?: Enumeration,
  status?: Status,
  originGeo?: Geo,
  defaultBoxType?: {
    shipmentBoxTypeId?: string,
    pseudoId?: string,
    description?: string,
    dimensionUomId?: string,
    boxLength?: 0,
    boxWidth?: 0,
    boxHeight?: 0,
    weightUomId?: string,
    boxWeight?: 0,
    defaultGrossWeight?: 0,
    capacityUomId?: string,
    boxCapacity?: 0,
    gatewayBoxId?: string,
  },
  amountUom?: Uom,
  assocs?: Array<ProductAssoc>,
  toAssocs?: Array<ProductAssoc>,
  contents?: Array<{
    productContentId?: string,
    productId?: string,
    contentLocation?: string,
    productContentTypeEnumId?: string,
    locale?: string,
    productFeatureId?: string,
    productStoreId?: string,
    fromDate?: string,
    thruDate?: string,
    description?: string,
    sequenceNum?: 0,
    userId?: string,
  }>,
  dimensions?: Array<{
    productId?: string,
    dimensionTypeId?: string,
    value?: 0,
    valueUomId?: string,
  }>,
  geos?: Array<{
    productId?: string,
    geoId?: string,
    productGeoPurposeEnumId?: string,
    description?: string,
    geo?: Geo
  }>,
  identifications?: Array<{
    productId?: string,
    productIdTypeEnumId?: string,
    idValue?: string,
  }>,
  parties?: Array<{
    productId?: string,
    partyId?: string,
    roleTypeId?: string,
    fromDate?: string,
    thruDate?: string,
    sequenceNum?: 0,
    comments?: string,
    otherPartyItemName?: string,
    otherPartyItemId?: string,
    party?: Party,
    role?: {
      roleTypeId?: string,
      parentTypeId?: string,
      description?: string,
    }
  }>,
  prices?: Array<{
    productPriceId?: string,
    productId?: string,
    productStoreId?: string,
    vendorPartyId?: string,
    customerPartyId?: string,
    priceTypeEnumId?: string,
    pricePurposeEnumId?: string,
    fromDate?: string,
    thruDate?: string,
    minQuantity?: 0,
    price?: 0,
    priceUomId?: string,
    termUomId?: string,
    taxInPrice?: string,
    taxAmount?: 0,
    taxPercentage?: 0,
    taxAuthorityId?: string,
    agreementId?: string,
    agreementItemSeqId?: string,
    otherPartyItemName?: string,
    otherPartyItemId?: string,
    comments?: string,
    quantityIncrement?: 0,
    quantityIncluded?: 0,
    quantityUomId?: string,
    preferredOrderEnumId?: string,
    supplierRatingTypeEnumId?: string,
    standardLeadTimeDays?: 0,
    canDropShip?: string,
  }>,
  categories?: Array<{
    productCategoryId?: string,
    productId?: string,
    fromDate?: string,
    thruDate?: string,
    comments?: string,
    sequenceNum?: 0,
    quantity?: 0,
  }>,
  features?: Array<{
    productId?: string,
    productFeatureId?: string,
    fromDate?: string,
    thruDate?: string,
    applTypeEnumId?: string,
    sequenceNum?: 0,
    amount?: 0,
    recurringAmount?: 0,
    featureProductId?: string,
    feature?: {
      productFeatureId?: string,
      productFeatureTypeEnumId?: string,
      description?: string,
      numberSpecified?: 0,
      numberUomId?: string,
      defaultAmount?: 0,
      defaultSequenceNum?: 0,
      abbrev?: string,
      idCode?: string,
      ownerPartyId?: string,
      numberPerPallet?: 0,
      perPalletTier?: 0,
      tiersPerPallet?: 0,
    }
  }>
}

export interface ProductAssoc {
  productId?: string,
  toProductId?: string,
  productAssocTypeEnumId?: string,
  fromDate?: string,
  thruDate?: string,
  sequenceNum?: 0,
  reason?: string,
  quantity?: 0,
  scrapFactor?: 0,
  instruction?: string,
  routingWorkEffortId?: string,
  type?: Enumeration,
  toProduct?: Product
}