import { ContactMech } from "./ContactMech";
import { Enumeration } from "./Enumeration";
import { Geo } from "./Geo";
import { Status } from "./Status";
import { Uom } from "./Uom";
export interface Facility {
    facilityId?: string;
    pseudoId?: string;
    facilityTypeEnumId?: string;
    parentFacilityId?: string;
    statusId?: string;
    ownerPartyId?: string;
    facilityName?: string;
    facilitySize?: number;
    facilitySizeUomId?: string;
    openedDate?: number;
    closedDate?: number;
    description?: string;
    geoId?: string;
    geoPointId?: string;
    countyGeoId?: string;
    stateGeoId?: string;
    assetAllowOtherOwner?: string;
    assetAllowIssueOverQoh?: string;
    assetInventoryLocRequire?: string;
    defaultDaysToShip?: number;
    externalId?: string;
    originId?: string;
    type?: Enumeration;
    parent?: {
        facilityId?: string;
        pseudoId?: string;
        facilityTypeEnumId?: string;
        parentFacilityId?: string;
        statusId?: string;
        ownerPartyId?: string;
        facilityName?: string;
        facilitySize?: number;
        facilitySizeUomId?: string;
        openedDate?: number;
        closedDate?: number;
        description?: string;
        geoId?: string;
        geoPointId?: string;
        countyGeoId?: string;
        stateGeoId?: string;
        assetAllowOtherOwner?: string;
        assetAllowIssueOverQoh?: string;
        assetInventoryLocRequire?: string;
        defaultDaysToShip?: number;
        externalId?: string;
        originId?: string;
    };
    status?: Status;
    owner?: {
        partyId?: string;
        pseudoId?: string;
        partyTypeEnumId?: string;
        disabled?: string;
        customerStatusId?: string;
        ownerPartyId?: string;
        externalId?: string;
        dataSourceId?: string;
        gatewayCimId?: string;
        comments?: string;
        shippingInstructions?: string;
        hasDuplicates?: string;
        lastDupCheckDate?: number;
        mergedToPartyId?: string;
        organization?: {
            partyId?: string;
            organizationName?: string;
            officeSiteName?: string;
            annualRevenue?: number;
            numEmployees?: number;
        };
        person?: {
            partyId?: string;
            salutation?: string;
            firstName?: string;
            middleName?: string;
            lastName?: string;
            personalTitle?: string;
            suffix?: string;
            nickname?: string;
            gender?: string;
            birthDate?: string;
            deceasedDate?: string;
            height?: number;
            weight?: number;
            mothersMaidenName?: string;
            maritalStatusEnumId?: string;
            employmentStatusEnumId?: string;
            residenceStatusEnumId?: string;
            occupation?: string;
        };
    };
    sizeUom?: Uom;
    geo?: Geo;
    geoPoint?: {
        geoPointId?: string;
        geoPointTypeEnumId?: string;
        description?: string;
        dataSourceId?: string;
        latitude?: number;
        longitude?: number;
        elevation?: number;
        elevationUomId?: string;
        information?: string;
    };
    certifications?: Array<{
        facilityCertificationId?: string;
        facilityId?: string;
        certificationTypeEnumId?: string;
        fromDate?: string;
        thruDate?: string;
        contactPartyId?: string;
        auditorPartyId?: string;
        auditorOrgPartyId?: string;
        auditStartDate?: number;
        auditEndDate?: number;
        auditScore?: string;
        certRegistrationId?: string;
        otherCertId?: string;
        documentLocation?: string;
    }>;
    contactMechs?: Array<ContactMech>;
    contents?: Array<{
        facilityContentId?: string;
        facilityId?: string;
        contentLocation?: string;
        facilityContentTypeEnumId?: string;
        contentDate?: number;
    }>;
    groups?: Array<{
        facilityId?: string;
        facilityGroupId?: string;
        fromDate?: number;
        thruDate?: number;
        sequenceNum?: number;
        group?: {
            facilityGroupId?: string;
            parentGroupId?: string;
            facilityGroupTypeEnumId?: string;
            description?: string;
        };
    }>;
    notes?: Array<{
        facilityId?: string;
        noteDate?: number;
        userId?: string;
        noteText?: string;
    }>;
    parties?: Array<{
        facilityId?: string;
        partyId?: string;
        roleTypeId?: string;
        fromDate?: number;
        thruDate?: number;
        party?: {
            partyId?: string;
            pseudoId?: string;
            partyTypeEnumId?: string;
            disabled?: string;
            customerStatusId?: string;
            ownerPartyId?: string;
            externalId?: string;
            dataSourceId?: string;
            gatewayCimId?: string;
            comments?: string;
            shippingInstructions?: string;
            hasDuplicates?: string;
            lastDupCheckDate?: number;
            mergedToPartyId?: string;
            organization?: {
                partyId?: string;
                organizationName?: string;
                officeSiteName?: string;
                annualRevenue?: number;
                numEmployees?: number;
            };
            person?: {
                partyId?: string;
                salutation?: string;
                firstName?: string;
                middleName?: string;
                lastName?: string;
                personalTitle?: string;
                suffix?: string;
                nickname?: string;
                gender?: string;
                birthDate?: string;
                deceasedDate?: string;
                height?: number;
                weight?: number;
                mothersMaidenName?: string;
                maritalStatusEnumId?: string;
                employmentStatusEnumId?: string;
                residenceStatusEnumId?: string;
                occupation?: string;
            };
        };
        role?: {
            roleTypeId?: string;
            parentTypeId?: string;
            description?: string;
        };
    }>;
    printers?: Array<{
        facilityId?: string;
        printerPurposeEnumId?: string;
        networkPrinterId?: string;
        printer?: {
            networkPrinterId?: string;
            serverHost?: string;
            serverPort?: number;
            printerName?: string;
            description?: string;
            location?: string;
            assetId?: string;
        };
    }>;
}
