import { Enumeration, Party, Status, Uom } from "./index";
export interface Shipment {
    shipmentId: String;
    shipmentTypeEnumId: String;
    statusId: String;
    fromPartyId: String;
    toPartyId: String;
    binLocationNumber: Number;
    productStoreId: String;
    priority: Number;
    entryDate: Number;
    shipAfterDate: Number;
    shipBeforeDate: Number;
    estimatedReadyDate: Number;
    estimatedShipDate: Number;
    estimatedArrivalDate: Number;
    latestCancelDate: Number;
    packedDate: Number;
    pickContainerId: String;
    estimatedShipCost: Number;
    costUomId: String;
    addtlShippingCharge: Number;
    addtlShippingChargeDesc: String;
    signatureRequiredEnumId: String;
    handlingInstructions: String;
    otherPartyOrderId: String;
    systemMessageRemoteId: String;
    externalId: String;
    originId: String;
    type: Enumeration;
    status: Status;
    fromParty: Party;
    toParty: Party;
    costUom: Uom;
    contents: Array<{
        shipmentContentId: String;
        shipmentContentTypeEnumId: String;
        shipmentId: String;
        productId: String;
        shipmentPackageSeqId: String;
        shipmentRouteSegmentSeqId: String;
        contentLocation: String;
        description: String;
        contentDate: Number;
        userId: String;
    }>;
    items: Array<{
        shipmentId: String;
        productId: String;
        quantity: Number;
    }>;
    packages: Array<{
        shipmentId: String;
        shipmentPackageSeqId: String;
        shipmentBoxTypeId: String;
        weight: Number;
        weightUomId: String;
        gatewayPackageId: String;
    }>;
    shipmentItemCount: Number;
    destinationFacilityId: String;
}
